apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
   app: {{ .Values.name }}
   chart: {{ template "devops.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  minReadySeconds: {{ .Values.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Values.name }}
      group: {{ .Values.group }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        chart: {{ template "devops.chart" . }}

    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "300m" | quote }}
              memory: {{ .Values.resources.limits.memory | default "0.1Gi" | quote }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "150m" | quote }}
              memory: {{ .Values.resources.requests.memory | default "0.1Gi" | quote }}
          env:
          {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end}}
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime-volume
            - mountPath: /etc/sysconfig/clock
              name: sysclock-volume
      volumes: {}
      {{- if .Values.antiAffinity.enabled }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.name }}
            topologyKey: "kubernetes.io/hostname"
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
