{{- $appName := .Values.name }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    chart: {{ template "devops.chart" . }}

  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
     
    {{- range .Values.ingress.routes }}
    - http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ $appName }}
              servicePort: 8080
        {{- end }}
      {{- end }}