name: "frontend-foo-prd"
replicaCount: 1

env:
  - name: ENV_VARIABLE
    value: "VALUE"

namespace: prd

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 150m
    memory: 100Mi

ingress:
  enabled: true
  host: amoremfigurinhasbh.com.br
  routes: 
    - paths:
        - path: /

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 50