name: "frontend-foo"
replicaCount: 1

env:
  - name: ENV_VARIABLE
    value: "VALUE"

namespace: hml

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 150m
    memory: 100Mi

ingress:
  enabled: true
  # annotations: 
  #   nginx.ingress.kubernetes.io/enable-cors: "true"
  #   nginx.ingress.kubernetes.io/rewrite-target: /jcot
  host: dev-amoremfigurinhasbh.com.br
  routes: 
    - paths:
        - path: /

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 50