# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v1

      - name: Terraform
        run: |
          terraform init ./pipelines/prepare/terraform
          terraform plan -var-file="inputs/terraform.tfvars" ./pipelines/prepare/terraform

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.


  bake:
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push - Backend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: /application/backend-foo
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: 417294130961.dkr.ecr.us-east-1.amazonaws.com/backend-foo:${{ github.sha }}

      - name: Build and push - Frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: /application/frontend-foo
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: 417294130961.dkr.ecr.us-east-1.amazonaws.com/frontend-foo:${{ github.sha }}