# This is a basic workflow to help you get started with Actions

name: CI-IAC

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ iac ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v1

      - name: Terraform
        run: |
          terraform init ./pipelines/prepare/terraform
          terraform plan -var-file="inputs/terraform.tfvars" ./terraform
          terraform apply -var-file="inputs/terraform.tfvars" --auto-approve ./terraform
